apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespace-creation-validator
webhooks:
  - name: validate.namespace-creation.com
    clientConfig:
      service:
        name: namespace-validator
        namespace: default
        path: "/validate"
      caBundle: ${ENCODED_CA}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    failurePolicy: "Fail"
    sideEffects: "None"