apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: muntashir/deployment-validator-control:4
          ports:
            - containerPort: 8443
          env:
             - name: DEPLOYMENT_PREFIX
               value: "prod-"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: webhook
