apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-validator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-validator
  template:
    metadata:
      labels:
        app: deployment-validator
    spec:
      containers:
        - name: deployment-validator
          image: muntashir/deployment-validator-control:v1
          ports:
            - containerPort: 8443
          env:
            - name: TLS_CERT
              value: "/etc/webhook/certs/tls.crt"
            - name: TLS_KEY
              value: "/etc/webhook/certs/tls.key"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-validator
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: deployment-validator
